apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elasticsearch-gateway
  namespace: logging
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "elasticsearch.minikube.me"
    port:
      name: https-elasticsearch
      number: 443
      protocol: HTTPS
    tls:
      credentialName: hands-on-certificate
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch-vs
  namespace: logging
spec:
  hosts:
  - "elasticsearch.minikube.me"
  gateways:
  - elasticsearch-gateway
  http:
  - route:
    - destination:
        host: elasticsearch
        port:
          number: 9200
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elasticsearch
  namespace: logging
spec:
  host: elasticsearch
  trafficPolicy:
    tls:
      mode: DISABLE