apiVersion: v2
name: recommendation-green
description: A Helm chart for the Recommendation microservice
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common
